[package]
name = "superdev"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "2.0.0"
solana-sdk = "2.0.0"
actix-web = "4.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.45.1"
spl-token = "7.0.0"

